# Generated by Django 5.0.2 on 2025-02-24 23:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['-created_date'], 'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AddField(
            model_name='request',
            name='after_image',
            field=models.ImageField(blank=True, null=True, upload_to='solved_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])], verbose_name='Фото решения'),
        ),
        migrations.AddField(
            model_name='request',
            name='before_image',
            field=models.ImageField(blank=True, null=True, upload_to='problem_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'bmp'])], verbose_name='Фото проблемы'),
        ),
        migrations.AddField(
            model_name='request',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отказа'),
        ),
        migrations.AlterField(
            model_name='request',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('new', 'Новая'), ('solved', 'Решена'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='request',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='request',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория'),
        ),
    ]
